version: "3.7"
services:
  nginx: 
    image: nginx:1.17
    ports: 
      - 8002:80
    volumes:
      - ./build/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./build/nginx/conf.d:/etc/nginx/conf.d
      - ./src:/var/www/html/
    depends_on:
      - php
  php:
    build: ./build/php/
    volumes:
      - ./src:/var/www/html/
    depends_on:
      - db
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
  node:
    image: "node:11-alpine"
    user: "node"
    working_dir: /home/node/app
    tty: true
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
